Repository kuzzleio/kuzzle-build, pull requests merged in 2018-06, with the labels that each got.

#36 Contributing
  CONTRIBUTING.md
Labels: changelog:exclude

#31 154 systemd
  setup.sh
Labels: changelog:new-feature

#37 Fixes setup.sh on OSX
  setup.sh
Labels: changelog:bug-fix
